# Generated by Django 5.1.7 on 2025-04-09 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0013_rename_category_item_section_and_more'),
        ('stores', '0003_remove_store_id_alter_store_code'),
        ('suppliers', '0002_remove_supplier_id_alter_supplier_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales_date_start', models.DateField(blank=True, null=True)),
                ('sales_date_end', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='items.section')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stores.store')),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='items.subsection')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suppliers.supplier')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.orderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_purchase', models.DateField(blank=True, null=True)),
                ('stock_available', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('days_stock_available', models.IntegerField(default=0)),
                ('quantity_last_purchase', models.IntegerField(blank=True, null=True)),
                ('quantity_suggested', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_order', models.IntegerField(default=0)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('bonus', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='items.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_number', models.BigIntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('expected_date', models.DateField()),
                ('quantity_order', models.IntegerField()),
                ('quantity_received', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='items.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stores.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSystemItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_order', models.IntegerField()),
                ('quantity_received', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='items.item')),
                ('oc_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.ordersystem')),
            ],
        ),
    ]
