# Generated by Django 5.1.7 on 2025-04-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersystem_received_date_ordersystem_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersystem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
