# Generated by Django 5.1.7 on 2025-04-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordersystem_total_amount'),
        ('stores', '0003_remove_store_id_alter_store_code'),
        ('suppliers', '0002_remove_supplier_id_alter_supplier_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSystemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_number', models.BigIntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField()),
                ('expected_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('all_items_received', models.BooleanField(default=False)),
                ('received_on_time', models.BooleanField(default=False)),
                ('perfect_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stores.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suppliers.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderSystemItem',
        ),
    ]
