# Generated by Django 5.1.7 on 2025-04-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordersystemresult_delete_ordersystemitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersystemresult',
            name='all_items_received',
        ),
        migrations.RemoveField(
            model_name='ordersystemresult',
            name='perfect_order',
        ),
        migrations.RemoveField(
            model_name='ordersystemresult',
            name='received_on_time',
        ),
    ]
