# Generated by Django 5.1.7 on 2025-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_ordersystemresult_all_items_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersystemresult',
            name='all_items_received',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordersystemresult',
            name='perfect_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordersystemresult',
            name='received_on_time',
            field=models.SmallIntegerField(default=0),
        ),
    ]
