# Generated by Django 5.1.7 on 2025-04-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_days_stock_desired_order_total_amout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amout',
            new_name='total_amount',
        ),
    ]
