# Generated by Django 5.1.7 on 2025-04-14 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_total_amout_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oc_numbers_pending',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
