# Generated by Django 5.1.7 on 2025-05-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='days_stock_desired',
        ),
    ]
