# Generated by Django 5.1.7 on 2025-05-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_days_stock_desired'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='days_stock_desired',
            field=models.IntegerField(default=0),
        ),
    ]
