# Generated by Django 5.1.7 on 2025-09-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_itemgroupview'),
        ('orders', '0013_orderitem_days_stock_desired'),
        ('stores', '0003_remove_store_id_alter_store_code'),
        ('suppliers', '0002_remove_supplier_id_alter_supplier_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordersystem',
            constraint=models.UniqueConstraint(fields=('oc_number', 'item', 'store'), name='ordersystem_oc_item_store_uniq'),
        ),
    ]
