# Generated by Django 5.1.7 on 2025-03-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=50)),
                ('pack_size', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('min_size', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('category', models.CharField(blank=True, max_length=35, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=35, null=True)),
                ('nivel3', models.CharField(blank=True, max_length=35, null=True)),
                ('nivel4', models.CharField(blank=True, max_length=35, null=True)),
                ('nivel5', models.CharField(blank=True, max_length=35, null=True)),
                ('brand', models.CharField(blank=True, max_length=35, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('is_active_purchase', models.BinaryField(default=True)),
                ('is_active', models.BinaryField(default=True)),
                ('matriz_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suppliers.supplier')),
            ],
        ),
    ]
