# Generated by Django 5.1.7 on 2025-03-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('stores', '0002_store_active_alter_store_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemControlStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=9)),
                ('days_stock', models.IntegerField(default=0)),
                ('stock_min', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('stock_max', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('stock_available', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('stock_available_on', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='items.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stores.store')),
            ],
        ),
    ]
