# Generated by Django 5.1.7 on 2025-03-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemcontrolstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontrolstock',
            name='stock',
        ),
    ]
