# Generated by Django 5.1.7 on 2025-04-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_itemcontrolstock_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_active_purchase',
        ),
    ]
