# Generated by Django 5.1.7 on 2025-04-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_is_active_remove_item_is_active_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active_purchase',
            field=models.BooleanField(default=True),
        ),
    ]
