# Generated by Django 5.1.7 on 2025-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_is_active_item_is_active_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
