# Generated by Django 5.1.7 on 2025-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
