# Generated by Django 5.1.7 on 2025-04-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_item_id_alter_item_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_active',
            new_name='is_disabled',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_active_purchase',
            new_name='is_disabled_purchase',
        ),
    ]
