# Generated by Django 5.1.7 on 2025-04-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_rename_is_active_item_is_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontrolstock',
            name='item',
            field=models.ForeignKey(
                to='items.Item',
                on_delete=models.RESTRICT,
                to_field='code'
            ),
        ),
        migrations.AlterField(
            model_name='itemcontrolstock',
            name='store',
            field=models.ForeignKey(
                to='stores.Store',
                on_delete=models.RESTRICT,
                to_field='code'
            ),
        ),        
    ]
