# Generated by Django 5.1.7 on 2025-04-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_fix_item_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontrolstock',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemcontrolstock',
            name='store',
        ),
    ]
