# Generated by Django 5.1.7 on 2025-04-08 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_itemcontrolstock_item_and_more'),
        ('stores', '0003_remove_store_id_alter_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontrolstock',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='items.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcontrolstock',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='stores.store'),
            preserve_default=False,
        ),
    ]
