# Generated by Django 5.1.7 on 2025-04-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_section_subsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subcategory',
            new_name='subsection',
        ),
    ]
