# Generated by Django 5.1.7 on 2025-04-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_rename_category_item_section_and_more'),
        ('stores', '0003_remove_store_id_alter_store_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='items.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stores.store')),
            ],
        ),
    ]
