# Generated by Django 5.1.7 on 2025-04-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
    ]
