# Generated by Django 5.1.7 on 2025-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_remove_stock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_last_purchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_last_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
