# Generated by Django 5.1.7 on 2025-04-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_item_date_last_purchase_item_quantity_last_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontrolstock',
            name='date_last_purchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcontrolstock',
            name='quantity_last_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
