# Generated by Django 5.1.7 on 2025-04-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_itemcontrolstock_date_last_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_last_purchase',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity_last_purchase',
        ),
        migrations.AddField(
            model_name='item',
            name='ean',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
