# Generated by Django 5.1.7 on 2025-04-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontrolstock',
            name='sales_frequency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
