# Generated by Django 5.1.7 on 2025-05-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_itemcontrolstock_sales_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroupView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Item Group View',
                'verbose_name_plural': 'Item Group Views',
                'db_table': 'sales_item_group_view',
                'managed': False,
            },
        ),
    ]
