# Generated by Django 5.1.7 on 2025-09-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_itemgroupview'),
        ('stores', '0003_remove_store_id_alter_store_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcontrolstock',
            unique_together={('item', 'store')},
        ),
    ]
