# Generated by Django 5.1.7 on 2025-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
