# Generated by Django 5.1.7 on 2025-03-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.IntegerField(),
        ),
    ]
