# Generated by Django 5.1.7 on 2025-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Dia do calendário',
                'verbose_name_plural': 'Calendário',
            },
        ),
    ]
