# Generated by Django 5.1.7 on 2025-05-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_price_alter_sale_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGroupView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Sales Group View',
                'verbose_name_plural': 'Sales Group Views',
                'db_table': 'sales_group_view',
                'managed': False,
            },
        ),
    ]
