# Generated by Django 5.1.7 on 2025-08-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesgroupview'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
