# Generated by Django 5.1.7 on 2025-08-14 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_calendar_holiday_name_calendar_is_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(help_text='Identificador da loja', verbose_name='ID da Loja')),
                ('item_id', models.PositiveIntegerField(help_text='Identificador do produto/item', verbose_name='ID do Produto')),
                ('forecast_date', models.DateField(help_text='Data para qual a previsão é válida', verbose_name='Data da Previsão')),
                ('prophet_prediction', models.FloatField(blank=True, help_text='Previsão gerada pelo modelo Prophet', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Previsão Prophet')),
                ('arima_prediction', models.FloatField(blank=True, help_text='Previsão gerada pelo modelo ARIMA', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Previsão ARIMA')),
                ('holt_winters_prediction', models.FloatField(blank=True, help_text='Previsão gerada pelo modelo Holt-Winters', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Previsão Holt-Winters')),
                ('xgboost_prediction', models.FloatField(blank=True, help_text='Previsão gerada pelo modelo XGBoost', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Previsão XGBoost')),
                ('best_model', models.CharField(choices=[('Prophet', 'Prophet'), ('ARIMA', 'ARIMA'), ('Holt-Winters', 'Holt-Winters'), ('XGBoost', 'XGBoost')], help_text='Modelo que apresentou melhor performance', max_length=50, verbose_name='Melhor Modelo')),
                ('best_prediction', models.FloatField(help_text='Previsão do melhor modelo (valor a ser usado)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Previsão Final')),
                ('confidence_score', models.FloatField(blank=True, help_text='Score de confiança da previsão (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score de Confiança')),
                ('model_rmse', models.FloatField(blank=True, help_text='Root Mean Square Error do melhor modelo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='RMSE do Modelo')),
                ('model_mape', models.FloatField(blank=True, help_text='Mean Absolute Percentage Error do melhor modelo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='MAPE do Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('model_version', models.CharField(help_text='Versão/timestamp do modelo que gerou a previsão', max_length=20, verbose_name='Versão do Modelo')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se esta previsão está ativa', verbose_name='Ativo')),
                ('actual_sales', models.FloatField(blank=True, help_text='Vendas reais (para comparação posterior)', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Vendas Reais')),
                ('forecast_error', models.FloatField(blank=True, help_text='Diferença entre previsão e venda real (calculado automaticamente)', null=True, verbose_name='Erro da Previsão')),
            ],
            options={
                'verbose_name': 'Previsão de Vendas',
                'verbose_name_plural': 'Previsões de Vendas',
                'ordering': ['-forecast_date', 'store_id', 'item_id'],
                'indexes': [models.Index(fields=['store_id', 'item_id', 'forecast_date'], name='sales_sales_store_i_4bb3ea_idx'), models.Index(fields=['forecast_date'], name='sales_sales_forecas_67e2d8_idx'), models.Index(fields=['created_at'], name='sales_sales_created_cc89fc_idx'), models.Index(fields=['model_version'], name='sales_sales_model_v_8fd90c_idx'), models.Index(fields=['best_model'], name='sales_sales_best_mo_de4ac7_idx'), models.Index(fields=['is_active'], name='sales_sales_is_acti_6bf41a_idx')],
                'unique_together': {('store_id', 'item_id', 'forecast_date', 'model_version')},
            },
        ),
    ]
