# Generated by Django 5.1.7 on 2025-08-19 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesforecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesforecast',
            options={'ordering': ['-forecast_date', 'item_id', 'store_id'], 'verbose_name': 'Previsão de Vendas', 'verbose_name_plural': 'Previsões de Vendas'},
        ),
        migrations.RemoveIndex(
            model_name='salesforecast',
            name='sales_sales_store_i_4bb3ea_idx',
        ),
        migrations.AlterUniqueTogether(
            name='salesforecast',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='brand',
            field=models.CharField(default=0, help_text='Marca do produto', max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='category',
            field=models.CharField(default=0, help_text='Categoria do produto', max_length=100, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='linear_regression_prediction',
            field=models.FloatField(blank=True, help_text='Previsão gerada pelo modelo Linear Regression', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Previsão Linear Regression'),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='model_mae',
            field=models.FloatField(default=0, help_text='Mean Absolute Error do melhor modelo', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='MAE do Melhor Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='random_forest_prediction',
            field=models.FloatField(blank=True, help_text='Previsão gerada pelo modelo Random Forest', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Previsão Random Forest'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='best_model',
            field=models.CharField(choices=[('arima', 'ARIMA'), ('holt_winters', 'Holt-Winters'), ('linear_regression', 'Linear Regression'), ('prophet', 'Prophet'), ('random_forest', 'Random Forest'), ('xgboost', 'XGBoost')], help_text='Modelo que apresentou melhor performance (menor MAE)', max_length=50, verbose_name='Melhor Modelo'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='model_version',
            field=models.CharField(default='1.0', help_text='Versão/timestamp do modelo que gerou a previsão', max_length=20, verbose_name='Versão do Modelo'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='store_id',
            field=models.PositiveIntegerField(blank=True, help_text='Identificador da loja (null = agregado todas as lojas)', null=True, verbose_name='ID da Loja'),
        ),
        migrations.AlterUniqueTogether(
            name='salesforecast',
            unique_together={('item_id', 'store_id', 'forecast_date', 'model_version')},
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['item_id', 'store_id', 'forecast_date'], name='sales_sales_item_id_8fabae_idx'),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['category'], name='sales_sales_categor_9e63a2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['brand'], name='sales_sales_brand_5814af_idx'),
        ),
    ]
