# Generated by Django 5.1.7 on 2025-10-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_salesforecast_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesforecast',
            unique_together={('item_id', 'store_id', 'forecast_date')},
        ),
    ]
