# Generated by Django 5.1.7 on 2025-05-26 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('report_negative_availability', models.BooleanField(default=True)),
                ('report_orders_awaiting_confirmation', models.BooleanField(default=True)),
                ('open_default_page', models.CharField(choices=[('dashboard', 'Dashboard'), ('order', 'Ordem de Compra')], max_length=20)),
                ('enable_chatbot', models.BooleanField(default=True)),
                ('chatbot_allowed_groups', models.ManyToManyField(blank=True, related_name='companies_with_chatbot', to='auth.group')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
        ),
    ]
