# Generated by Django 5.1.7 on 2025-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='report_items_with_stock_no_sales',
            field=models.BooleanField(default=True),
        ),
    ]
