# Generated by Django 5.1.7 on 2025-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companysettings_report_items_with_stock_no_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='view_sales_last_weeks',
            field=models.BooleanField(default=True),
        ),
    ]
