# Generated by Django 5.1.7 on 2025-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
