# Generated by Django 5.1.7 on 2025-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_active_alter_store_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
